### ISSUE TITLE
Generating client code for PHP docs

### ISSUE THREAD

**Issue by zinuga** [grpc/grpc.github.io#214] opened 2016-06-24 17:17 UTC
http://www.grpc.io/docs/tutorials/basic/php.html#generating-client-code
Generating the packages for a php client as described above is very awkward and doesn't work (Dale can provide more info on that point)
Basically, for PHP, client generation span different build system (gem, rake).
It includes some 3rd party library ("drslump")
(was pretty difficult to use;  couln't get it working as of yet)

**Comment by stanley-cheung** [comment] 2016-06-24 17:41
This is because we are currently using a 3rd party protobuf solution before we have official proto3 support. This will all go away once we are able to switch to proto3. 

But in any case can you provide some log on what doesn't work ?

**Comment by ckurz-va** [comment] 2016-06-24 21:33
I can chime in here. 

I pushed a docker image of our process. It's available at docker.io/toad008/datariver-php. The image is based of php5.5, and installs all the things we found we needed to get things working. It also copies in our proto file, and a test.php file we have been trying to get things to work with. 

If you pull the image, and run command line in it (docker run -ti toad008/datariver-php /bin/bash) you can find our protofle at /datariver/datariver.proto. The test file is in the same directory beside it, and the datariver.php file is what was generated by the protoc command during the docker build. The Dockerfile is not in the repo (as I don't have autobuild set up) but I can provide that as needed.

The error we are seeing is PHP fatal error, call to undefined method Grpc\ChannelCredientals::setDefaultRootsPem() in /datariver/vendor/grpc/grpc/src/php/lib/Grpc/BaseStub.php on line 61

This might just be a factor of a mismatch in versions between some of the third party plugin things happening, and grpc. 

Given the node.js option took < 3 hours to go from the proto file and nothing installed to a working test file, and C# was a couple days (largely getting a windows virtual machine and visual studio up and running) the complexity of the php implementation case is a touch shocking. Also the documentation for it seems disjointed and difficult to follow.

**Comment by stanley-cheung** [comment] 2016-06-24 22:07
Sorry to hear about your experience. The error you got is indeed a mismatch between the composer version vs the PHP extension version. In your `composer.json` file when you pull in `grpc/grpc` as dependency, can you make sure the version is `dev-release-0_14`?

**Comment by ckurz-va** [comment] 2016-06-27 15:52
That does seem to allow the code to all compile as expected. Thanks!

**Comment by ckurz-va** [comment] 2016-06-27 15:53
I believe we can call this issue closed and resolved, as we are no longer blocked, however, I think an issue to update / improve documentation is likely still valuable.

**Comment by ckurz-va** [comment] 2016-06-27 22:12
We are hitting another big problem.

We have an SSL encrypted server. In C# and node.js, you create the Channel Credentials as SslCredentials with null args, indicating the server is doing the ssl work. In the php case, we can't create SslCredentials without a pem file, which we would rather not distribute with our code. 

How do we generate the SSL channel creds in php like we do in C#? 

C#:
```
var channelCredentials = new SslCredentials(null, null);
var channel = new Channel("directory-sandbox.vendasta.com", 23000, channelCredentials);
var client = new DataRiver.DataRiverClient(channel);
```

PHP:
```
$channel_credentials = Grpc\ChannelCredentials::createSsl(null);
$client = new datariver\DataRiverClient('directory-sandbox.vendasta.com:23000', [
    'credentials' => $channel_credentials
]);
```
Returns: 
```
D0627 22:11:07.528069956       7 channel.c:175]              Initialized secure channel
E0627 22:11:07.528152759       7 load_file.c:84]             Could not open file /usr/share/grpc/roots.pem (error = No such file or directory).
E0627 22:11:07.528172536       7 security_connector.c:735]   Could not get default pem root certs.
```
Attempts to use that client then give us a details error of: "Failed to create security connector."

**Comment by stanley-cheung** [comment] 2016-06-27 22:33
Let me take a look. I suspect this is an issue we fixed with the upcoming 0.15 release. But I will confirm

**Comment by stanley-cheung** [comment] 2016-06-28 00:06
I was able to reproduce the exact error on 0.14 and verified that the issue is fixed in 0.15. Please wait for a couple of days and the latest release should be up. Sorry about this.

**Comment by stanley-cheung** [comment] 2016-06-28 22:21
PHP v0.15.0 has been released. Can you please update your `composer.json` file to say `"grpc/grpc": "v0.15.0"`. And make sure your `sudo pecl install grpc-beta` command picked up the latest release `0.15.0` (just by reading the log output, the last few lines should be enough).

Thanks.

**Comment by ckurz-va** [comment] 2016-06-29 16:47
Made more progress. 

The 0.15.0 seems to have gotten us past the creating server ssl creds call we were making. The newest error I'm hitting is: `PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'datariver\ListingResponse' does not have a method 'deserialize' in /datariver/vendor/grpc/grpc/src/php/lib/Grpc/AbstractCall.php on line 125`
It looks like the github code for github.com/stanlet-cheung/Protobuf-PHP on git hub has deserialize defined, basically as a wrapper on parse, but the message definition we are pulling from (which I think is the datto protobuf-php, which imports DrSlump, instead of the Stanley Cheung fork of DrSlump) does not have that deserialize method. 

I am experimenting to confirm that is what is happening (largely by moving some libs around) but the differences in these protobuf-php libs is adding quick a bit of complication to the php implementation case.

**Comment by stanley-cheung** [comment] 2016-06-29 16:54
Yes, known issue. You need to add this block in your `composer.json` file.

```
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/stanley-cheung/Protobuf-PHP"
    }
  ],
```

See https://github.com/grpc/grpc/blob/master/examples/php/composer.json. This will override the Protobuf-PHP implementation with our fork. We are in the process of getting our change merge upstream.

**Comment by ckurz-va** [comment] 2016-06-29 16:55
yeah, the lib directory copy worked great, but I like the composer change to resolve the issue. I'm seeing the response as expected from my server now, so I'm feeling very close to the end here. Thanks again for all the prompt responses, and good information!

**Closed** 2016-07-08 03:31 UTC
